server {
    listen 80;
    server_name comunidadeppg.com.br www.comunidadeppg.com.br;

    root /usr/share/nginx/html;
    index index.html;

    # Vue Router (SPA) — redireciona tudo pro index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~ /\. {
        deny all;
    }
}
